### ISSUE TITLE
overdose theme 적용 중 발생한 에러 입니다.

### ISSUE THREAD

**Issue by SungmanHan** [HyunSeob/hexo-theme-overdose#53]
$ cd your/hexo/directory
$ git clone https://github.com/HyunSeob/hexo-theme-overdose.git themes/overdose
$ npm install --save hexo-renderer-jade 
$ cp _config.yml.example _config.yml
$ hexo server

로컬에서 실행 시 발생하는 문제인데…. 저 부분에서 왜 발생하는지 이유를 잘 모르겠네요….

ERROR Process failed: layout/post.pug
Error: /Users/sunghan/Myblog/themes/overdose/layout/post.pug:16:35
    14|             - var banner = bannerOf(post) || theme.default.url;
    15|             .related-posts__item__background(style={
  > 16|               'background-image': `url('${banner}')`
------------------------------------------^
    17|             })
    18|             .related-posts__item__overlay
    19|             span.related-posts__item__title= post.title || 'Untitled'

Syntax Error: Unexpected character '`'
    at makeError (/Users/sunghan/Myblog/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:52:15)
    at Lexer.assertExpression (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:71:12)
    at Lexer.attrs (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1034:18)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.advance (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1303:15)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.getTokens (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1322:12)
    at Object.lex (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:12:42)
    at Function.loadString [as string] (/Users/sunghan/Myblog/node_modules/pug-loader/index.js:39:24)
    at compileBody (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:55:18)
    at Object.exports.compile (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:152:16)
    at Function.pugCompile [as compile] (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/lib/renderer.js:6:16)
    at Theme._View.View.View._precompile (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:117:31)
    at Theme._View.View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:71:20)
    at file.read.then.result (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/sunghan/Myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:614:10)
ERROR Process failed: layout/includes/article.pug
Error: /Users/sunghan/Myblog/themes/overdose/layout/includes/article.pug:38:-38
    36|     a.article__author__link(
    37|       href=theme.profile.link
  > 38|       title=`About ${config.author}`
    39|       rel="author"
    40|     )= config.author
    41|     p.article__author__desc= theme.profile.description || config.description

Syntax Error: Unexpected character '`'
    at makeError (/Users/sunghan/Myblog/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:52:15)
    at Lexer.assertExpression (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:71:12)
    at Lexer.attrs (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1034:18)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.advance (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1303:15)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.getTokens (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1322:12)
    at Object.lex (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:12:42)
    at Function.loadString [as string] (/Users/sunghan/Myblog/node_modules/pug-loader/index.js:39:24)
    at compileBody (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:55:18)
    at Object.exports.compile (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:152:16)
    at Function.pugCompile [as compile] (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/lib/renderer.js:6:16)
    at Theme._View.View.View._precompile (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:117:31)
    at Theme._View.View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:71:20)
    at file.read.then.result (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/sunghan/Myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:614:10)
ERROR Process failed: layout/includes/post-list.pug
Error: /Users/sunghan/Myblog/themes/overdose/layout/includes/post-list.pug:47:33
    45|           - var banner = bannerOf(post) || theme.default.url;
    46|           .post-list__item__link__background(style={
  > 47|             'background-image': `url('${banner}')`
----------------------------------------^
    48|           })
    49|       .post-list__item__col-2
    50|         .post-list__item__meta

Syntax Error: Unexpected character '`'
    at makeError (/Users/sunghan/Myblog/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:52:15)
    at Lexer.assertExpression (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:71:12)
    at Lexer.attrs (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1034:18)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.advance (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1303:15)
    at Lexer.callLexerFunction (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1266:23)
    at Lexer.getTokens (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:1322:12)
    at Object.lex (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug-lexer/index.js:12:42)
    at Function.loadString [as string] (/Users/sunghan/Myblog/node_modules/pug-loader/index.js:39:24)
    at compileBody (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:55:18)
    at Object.exports.compile (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/node_modules/pug/lib/index.js:152:16)
    at Function.pugCompile [as compile] (/Users/sunghan/Myblog/node_modules/hexo-renderer-pug/lib/renderer.js:6:16)
    at Theme._View.View.View._precompile (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:117:31)
    at Theme._View.View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/index.js:71:20)
    at file.read.then.result (/Users/sunghan/Myblog/node_modules/hexo/lib/theme/processors/view.js:14:14)
    at tryCatcher (/Users/sunghan/Myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sunghan/Myblog/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by TheBestJohn** [comment]
템플릿에 삽입되는 설정 파일에 백틱이있는 것 같습니다. _config.yaml 파일에서 "`"검색을 수행하십시오.

**Comment by nayunhwan** [comment]
`hexo-renderer-pug`를 설치했을 때 해당과 같은 오류가 발생합니다.
`hexo-renderer-jade`를 설치해주세요.

```
$ npm install --save hexo-renderer-jade
```

---
This error occurs when had installed `hexo-renderer-pug`.
You need to install `hexo-renderer-jade` instead of `hexo-renderer-pug`
