### ISSUE TITLE
overdoes theme로 설정후 hexo 실행 시 발생 에러입니다.  

### ISSUE THREAD

**Issue by ghost** [HyunSeob/hexo-theme-overdose#54]
1. themes 디렉토리에 git clone 하고
2. _config.yml.example --> _config.yml 로 변경 후
3. $ npm install --save hexo-renderer-jade
4. $hexo server

실행 시킨 후 난 에러입니다. 

Unhandled rejection TypeError: /Users/zero2hex/Documents/kyeongin/git_blog/blog/themes/overdose/layout/includes/head.pug:9
    7| - pageTitle = pageTitle ? pageTitle += ' | ' + config.title : config.title;
    8| - var banner = bannerOf(page) || theme.default.url;
  > 9| -
    10|   var description = truncate(
    11|     strip_html(page.content) || config.description || theme.profile.description,
    12|     {

str must be a string!
    at Object.truncate (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/hexo-util/lib/truncate.js:4:38)
    at eval (eval at wrap (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:26:19)
    at template (eval at wrap (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:728:72)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/zero2hex/Documents/kyeongin/git_blog/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:449:10)
    at resume_ (_stream_readable.js:888:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

아래에 같은 이슈가 있었지만, 시간이 조금 지났어서 다시 문의드립니다.

**Comment by kaylais** [comment]
저도 같은 이슈 발생하고 있습니다.

**Comment by miknai** [comment]
I get the exact same error...
